/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ayckermann.discordbot;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class MessageForm extends javax.swing.JFrame {

    /**
     * Creates new form MessageForm
     */
    private Database db = new Database();
    DiscordBot jda = new DiscordBot();
    
    public MessageForm() throws SQLException {
        initComponents();
        tblMessage.getColumnModel().getColumn(0).setMaxWidth(5);
        tblMessage.getColumnModel().getColumn(1).setMinWidth(100);
        tblMessage.getColumnModel().getColumn(2).setMinWidth(200);
        

        txtIdMessage.setVisible(false);
        this.dataMessage();

 
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMessage = new javax.swing.JTable();
        txtMsgMessage = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRespondMessage = new javax.swing.JTextArea();
        btnAddMessage = new javax.swing.JButton();
        labelMsgMessage = new javax.swing.JLabel();
        labelRespondMessage = new javax.swing.JLabel();
        btnDeleteMessage = new javax.swing.JButton();
        btnUpdateMessage = new javax.swing.JButton();
        txtIdMessage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMessage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Message", "Respond"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMessageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMessage);

        txtMsgMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgMessageActionPerformed(evt);
            }
        });

        txtRespondMessage.setColumns(20);
        txtRespondMessage.setRows(5);
        jScrollPane2.setViewportView(txtRespondMessage);

        btnAddMessage.setBackground(new java.awt.Color(0, 102, 0));
        btnAddMessage.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMessage.setText("ADD");
        btnAddMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMessageActionPerformed(evt);
            }
        });

        labelMsgMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMsgMessage.setText("Message");

        labelRespondMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRespondMessage.setText("Respond");

        btnDeleteMessage.setBackground(new java.awt.Color(153, 0, 0));
        btnDeleteMessage.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteMessage.setText("DELETE");
        btnDeleteMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMessageActionPerformed(evt);
            }
        });

        btnUpdateMessage.setBackground(new java.awt.Color(153, 153, 0));
        btnUpdateMessage.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateMessage.setText("UPDATE");
        btnUpdateMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMessageActionPerformed(evt);
            }
        });

        txtIdMessage.setEditable(false);
        txtIdMessage.setText("id");
        txtIdMessage.setFocusable(false);
        txtIdMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRespondMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelMsgMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnUpdateMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(243, 243, 243)
                                    .addComponent(btnDeleteMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtMsgMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMsgMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMsgMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRespondMessage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void dataMessage(){

        try {
            ResultSet resultSet =  db.load("SELECT * FROM msg_respond", null);
            DefaultTableModel tableModel = (DefaultTableModel)tblMessage.getModel();
            tableModel.setRowCount(0); //reset data
            
            while (resultSet.next()) {
                int id = resultSet.getInt("idMessage");
                String message =  resultSet.getString("message");
                String respond = resultSet.getString("respond");

                Object[] rowData = {id,message,respond};
                tableModel.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MessageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFieldMessage(){
        int row = tblMessage.getSelectedRow();
        String id = Integer.toString((int)tblMessage.getValueAt(row,0));
        txtIdMessage.setText(id);
        txtMsgMessage.setText((String)tblMessage.getValueAt(row,1));
        txtRespondMessage.setText((String)tblMessage.getValueAt(row,2));
    }
        
    private void txtMsgMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgMessageActionPerformed

    private void btnAddMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMessageActionPerformed
        if(txtMsgMessage.getText().isBlank() || txtRespondMessage.getText().isBlank() ){
            JOptionPane.showInternalMessageDialog(null, "Ada data yang masih kosong");
        }
        else{
            Object[] rowData = {txtMsgMessage.getText(),txtRespondMessage.getText() };
            db.edit("INSERT INTO msg_respond (message,respond) VALUES(?,?)", rowData);
            this.dataMessage();
      
        }
    }//GEN-LAST:event_btnAddMessageActionPerformed

    private void btnDeleteMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMessageActionPerformed
        int row = tblMessage.getSelectedRow();
        
        int id = (int)tblMessage.getValueAt(row,0);

        Object[] data = {Integer.toString(id)};
      
        db.edit("DELETE FROM msg_respond WHERE idMessage=?", data);
        this.dataMessage();
     
    }//GEN-LAST:event_btnDeleteMessageActionPerformed

    private void btnUpdateMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMessageActionPerformed
        Object[] data = {txtMsgMessage.getText(),txtRespondMessage.getText(), txtIdMessage.getText()};
    
        db.edit("UPDATE msg_respond SET message =?, respond=? WHERE idMessage=?", data);
        this.dataMessage();
  
    }//GEN-LAST:event_btnUpdateMessageActionPerformed

    private void tblMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMessageMouseClicked
        setFieldMessage();
    }//GEN-LAST:event_tblMessageMouseClicked

    private void txtIdMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMessageActionPerformed
    

    /**
     * @param args the command line arguments
     */

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MessageForm().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMessage;
    private javax.swing.JButton btnDeleteMessage;
    private javax.swing.JButton btnUpdateMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMsgMessage;
    private javax.swing.JLabel labelRespondMessage;
    private javax.swing.JTable tblMessage;
    private javax.swing.JTextField txtIdMessage;
    private javax.swing.JTextField txtMsgMessage;
    private javax.swing.JTextArea txtRespondMessage;
    // End of variables declaration//GEN-END:variables
}
